name: Publish to Packagist

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Composer dependencies
        run: composer install --no-progress

      - name: Publish to Packagist
        uses: mnavarrocarter/packagist-update@v1.0
        with:
          username: ${{ secrets.PACKAGIST_USERNAME }}
          api_token: ${{ secrets.PACKAGIST_API_TOKEN }}
          package_name: 'marcohoutmandev/rmt-versioning'